name: fs2sshbuild

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

env:
  SBT: ./sbt
  JDK: 1.8
  REPO_SLUG: ${{ github.repository }}
  ENCRYPTION_PASSWORD: ${{ secrets.ENCRYPTION_PASSWORD }}

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest]
        scala: [2.12.10, 2.13.1]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Set up JDK ${{ env.JDK }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JDK }}
      - name: Setup Git Actor
        run: git config github.actor slamdata-bot
      - name: Compile and test
        run: $SBT ++${{ matrix.scala }} ci 
      - name: Upload target
        uses: actions/upload-artifact@v1
        with:
          name: target-${{ matrix.scala }}
          path: target

  publishandtag:
    name: Publish and Tag
    needs: [build]
    if: github.event_name != 'pull_request' && (contains(github.head_ref, 'backport/v.*') || contains(github.head_ref, 'master'))
    strategy:
      matrix:
        scala: [2.12.10]
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Download target artifacts
        uses: actions/download-artifact@v1
        with:
          name: target-${{ matrix.scala }}
      - name: Set up JDK ${{ env.JDK }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JDK }}
      - name: Setup Git Actor
        run: git config github.actor slamdata-bot
      - name: Transfer common resources
        run: $SBT transferCommonResources
      - name: Export common secrets
        run: $SBT exportSecretsForActions
      - name: Common setup
        run: ./scripts/core/commonSetup
      - name: Run publish and tag
        run: ./scripts/fs2SshPublishAndTag

  commonResources:
    name: Auto Merge
    if: github.event_name == 'pull_request' && contains(github.head_ref, 'version-bump')
    needs: [build]
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Download target artifacts
        uses: actions/download-artifact@v1
        with:
          name: target
      - name: Setup Git Actor
        run: git config github.actor slamdata-bot
      - name: Set up JDK ${{ env.JDK }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JDK }}
      - name: Install ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Install common resources
        run: $SBT transferCommonResources
      - name: Export common secrets
        run: $SBT exportSecretsForActions
      - name: Common setup
        run: ./scripts/core/commonSetup
      - name: Set env vars
        run: |
          echo ::set-env name=VERSIONS::$(git diff HEAD^1 | grep -e '^[-+][0-9]' | sed 's/^[+\-]//' | sed 's/\.[0-9]*$//' | uniq | wc -l)
          echo ::set-env name=CLONE_DIR::$(mktemp -d "/tmp/slamdata-bump.XXXXXXXX")
          echo ::set-env name=IS_REVISION_LABEL::${{ contains(github.event.pull_request.labels.*.name, 'revision') }}
          echo ::set-env name=PR_NUMBER::$(echo "$GITHUB_REF" | cut -d'/' -f3)
      - name: Check auto merge
        run: ./scripts/core/checkAndAutoMerge
